from datetime import datetime
import os
# Platform Imports
from connectors.rdbms_postgresql import create_connection
from common.platform_settings import build_platform_variables
from common.platform_settings import build_platform_config
from common.auditerror_mgmt import process_auditerror_details
